POST http://localhost:8000/raw
#  POST https://ssn-zilliqa.moonlet.network/raw
# POST https://api.zilliqa.com
# POST https://node-zilliqa.moonlet.network/api
Content-Type: application/json
# CF-Connecting-IP: 192.168.100.100

{"method":"GetRawDSBlock","params":["3528"],"jsonrpc":"2.0","id":1}