on:
  release:
    types:
      - published
name: Docker image
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/moonlet/zilliqa-rpc-gateway/rpc-gateway:${{ github.event.release.tag_name }}
      - name: Publish docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u moonlet-dev --password-stdin
          docker push docker.pkg.github.com/moonlet/zilliqa-rpc-gateway/rpc-gateway:${{ github.event.release.tag_name }}
